spring:
  application:
    name: image-to-excel
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 2GB

server:
  port: 8080

# Google Cloud Vision API 설정
google:
  vision:
    api-key: ${GOOGLE_CLOUD_API_KEY:}
    api-url: https://vision.googleapis.com/v1/images:annotate
